export const productList=
    {
      food:{
          new:[
            {id:1,name:'a new food',price:30,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp ppppppp fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b new food',price:30,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c new food',price:30,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
            ],
          apple:[
            {id:1,name:'a apple',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b apple',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c apple',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
         orange:[
            {id:1,name:'a orange',price:50,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b orange',price:50,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c orange',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
         banana:[
            {id:1,name:'a banana',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b banana',price:70,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c banana',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
      },
      toys:{
       new:[
            {id:1,name:'a new toys',price:20,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b new toys',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c new toys',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
            ],
        bear:[
            {id:1,name:'a bear',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b bear',price:400,prevPrice:420,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c bear',price:40,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
        robot:[
            {id:1,name:'a robot',price:60,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b robot',price:40,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c robot',price:40,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
        car:[
            {id:1,name:'a car',price:40,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b car',price:78,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c car',price:40,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
      },
      others:{
        new:[
            {id:1,name:'a new others',price:40,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b new others',price:40,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c new others',price:49,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:4,name:'d new others',price:50,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
            ],
        chopper:[
            {id:1,name:'a chopper',price:40,prevPrice:100,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b chopper',price:400,prevPrice:500,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c chopper',price:40,prevPrice:70,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:4,name:'d chopper',price:40,prevPrice:70,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:5,name:'e chopper',price:40,prevPrice:70,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:6,name:'f chopper',price:100,prevPrice:160,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:7,name:'g chopper',price:40,prevPrice:60,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:8,name:'h chopper',price:40,prevPrice:60,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:9,name:'i chopper',price:200,prevPrice:260,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:10,name:'j chopper',price:40,prevPrice:60,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:11,name:'k chopper',price:40,prevPrice:60,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:12,name:'l chopper',price:40,prevPrice:60,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:13,name:'m chopper',price:40,prevPrice:60,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:14,name:'n chopper',price:40,prevPrice:60,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
          ],
         earsphone:[
            {id:1,name:'a earsphone',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b earsphone',price:230,prevPrice:280,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c earsphone',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
         cup:[
            {id:1,name:'a cup',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b cup',price:30,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c cup',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
         box:[
            {id:1,name:'a box',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b box',price:70,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c box',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
         pan:[
            {id:1,name:'a pan',price:10,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b pan',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c pan',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
        ball:[
            {id:1,name:'a ball',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b ball',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c ball',price:20,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
         tap:[
            {id:1,name:'a tap',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:2,name:'b tap',price:40,prevPrice:80,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"},
            {id:3,name:'c tap',price:450,prevPrice:500,comeFrom:"USA",description:"this is description.jnjdnjnjn asdasda aaaaa bbbbbb cccccc dddddd eeeeee ppppp ----- ===== [[[[ ]]]] ] lll ;; ' ' ' o 8 7980 dspppppp pppppp ppppppppp pppppppppppp pppppppppppp ppppppppppp ppppppppp ppppppppp pppppp pppppp pppppp pppppppsda fg dfg   ghfg hgf h fgh fgh f gjh fg h fgh fgh fgh fg hfgh gfh fgh fgh asdsdggbkmmokmdfkodmo jsndj nanjdnjf ndjsnjcj aonxacna jncjnaj cnjanscj najcnan jnajcncnjanjanjc njacnajxcjan caincjacan"}
          ],
      }
    }

export const subNavigationList={//fake data
        food:[
            {id:1,name:'new'},
            {id:2,name:'apple'},
            {id:3,name:'orange'},
            {id:4,name:'banana'}
        ],
        toys:[
            {id:1,name:'new'},
            {id:2,name:'bear'},
            {id:3,name:'robot'},
            {id:4,name:'car'}
        ],
        others:[
            {id:1,name:'new'},
            {id:2,name:'chopper'},
            {id:3,name:'earsphone'},
            {id:4,name:'cup'},
            {id:5,name:'box'},
            {id:6,name:'pan'},
            {id:7,name:'ball'},
            {id:8,name:'tap'}
        ]
    }


export const list_to_display_at_home=[//fake data
        {
          name:"food",
          value:[
             "new","apple"
          ]
        },
        {
          name:"others",
          value:[
             "new","chopper","cup","earsphone",
             "box","pan","ball","tap"
          ]
        }      
      ]