export const productList=
    {
      food:{
          new:[
            {id:1,name:'a_new_food',price:30},
            {id:2,name:'b_new_food',price:30},
            {id:3,name:'c_new_food',price:30}
            ],
          apple:[
            {id:1,name:'a_apple',price:40},
            {id:2,name:'b_apple',price:40},
            {id:3,name:'c_apple',price:40}
          ],
         orange:[
            {id:1,name:'a_orange',price:50},
            {id:2,name:'b_orange',price:50},
            {id:3,name:'c_orange',price:40}
          ],
         banana:[
            {id:1,name:'a_banana',price:40},
            {id:2,name:'b_banana',price:70},
            {id:3,name:'c_banana',price:40}
          ],
      },
      toys:{
       new:[
            {id:1,name:'a_new_toys',price:20},
            {id:2,name:'b_new_toys',price:40},
            {id:3,name:'c_new_toys',price:40}
            ],
        bear:[
            {id:1,name:'a_bear',price:40},
            {id:2,name:'b_bear',price:400},
            {id:3,name:'c_bear',price:40}
          ],
        robot:[
            {id:1,name:'a_robot',price:60},
            {id:2,name:'b_robot',price:40},
            {id:3,name:'c_robot',price:40}
          ],
        car:[
            {id:1,name:'a_car',price:40},
            {id:2,name:'b_car',price:78},
            {id:3,name:'c_car',price:40}
          ],
      },
      others:{
        new:[
            {id:1,name:'a_new_others',price:40},
            {id:2,name:'b_new_others',price:40},
            {id:3,name:'c_new_others',price:49},
            {id:4,name:'d_new_others',price:50}
            ],
        chopper:[
            {id:1,name:'a_chopper',price:40},
            {id:2,name:'b_chopper',price:400},
            {id:3,name:'c_chopper',price:40},
            {id:4,name:'d_chopper',price:40},
            {id:5,name:'e_chopper',price:40},
            {id:6,name:'f_chopper',price:100},
            {id:7,name:'g_chopper',price:40},
            {id:8,name:'h_chopper',price:40},
            {id:9,name:'i_chopper',price:200},
            {id:10,name:'j_chopper',price:40},
            {id:11,name:'k_chopper',price:40},
            {id:12,name:'l_chopper',price:40},
            {id:13,name:'m_chopper',price:40},
            {id:14,name:'n_chopper',price:40},
          ],
         earsphone:[
            {id:1,name:'a_earsphone',price:40},
            {id:2,name:'b_earsphone',price:230},
            {id:3,name:'c_earsphone',price:40}
          ],
         cup:[
            {id:1,name:'a_cup',price:40},
            {id:2,name:'b_cup',price:30},
            {id:3,name:'c_cup',price:40}
          ],
         box:[
            {id:1,name:'a_box',price:40},
            {id:2,name:'b_box',price:70},
            {id:3,name:'c_box',price:40}
          ],
         pan:[
            {id:1,name:'a_pan',price:10},
            {id:2,name:'b_pan',price:40},
            {id:3,name:'c_pan',price:40}
          ],
        ball:[
            {id:1,name:'a_ball',price:40},
            {id:2,name:'b_ball',price:40},
            {id:3,name:'c_ball',price:20}
          ],
         tap:[
            {id:1,name:'a_tap',price:40},
            {id:2,name:'b_tap',price:40},
            {id:3,name:'c_tap',price:450}
          ],
      }
    }

export const subNavigationList={//fake data
        food:[
            {id:1,name:'new'},
            {id:2,name:'apple'},
            {id:3,name:'orange'},
            {id:4,name:'banana'}
        ],
        toys:[
            {id:1,name:'new'},
            {id:2,name:'bear'},
            {id:3,name:'robot'},
            {id:4,name:'car'}
        ],
        others:[
            {id:1,name:'new'},
            {id:2,name:'chopper'},
            {id:3,name:'earsphone'},
            {id:4,name:'cup'},
            {id:5,name:'box'},
            {id:6,name:'pan'},
            {id:7,name:'ball'},
            {id:8,name:'tap'}
        ]
    }


export const list_to_display_at_home=[//fake data
        {
          name:"food",
          value:[
             "new","apple"
          ]
        },
        {
          name:"others",
          value:[
             "new","chopper","cup","earsphone",
             "box","pan","ball","tap"
          ]
        }      
      ]